name: savetheplanet
description: SaveThePlanet flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  rflutter_alert: ^1.0.3
  intro_slider: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
     - images/

  fonts:
     - family: Pacifico
       fonts:
         - asset: fonts/Pacifico-Regular.ttf

     - family: SourceSansPro
       fonts:
         - asset: fonts/SourceSansPro-Regular.ttf

     - family: Notable
       fonts:
          - asset: fonts/Notable-Regular.ttf

     - family: AmaticSC
       fonts:
             - asset: fonts/AmaticSC-Bold.ttf
